data {
  int d_int;
  real d_real;
  vector[d_int] d_vector;
  matrix[d_int, d_int] d_matrix;
  row_vector[d_int] d_row_vector;
  array[d_int] real d_real_array_1d;
  array[d_int, 2] real d_real_array_2d;
  array[d_int, 2, 3] real d_real_array_3d;
  array[d_int] vector[d_int] d_vector_array_1d;
  array[d_int, 2] vector[d_int] d_vector_array_2d;
  array[d_int, 2, 3] vector[d_int] d_vector_array_3d;
  array[d_int] matrix[d_int, d_int] d_matrix_array_1d;
  array[d_int] row_vector[d_int] d_row_vector_array_1d;
  array[d_int, 2] matrix[d_int, d_int] d_matrix_array_2d;
  array[d_int, 2] row_vector[d_int] d_row_vector_array_2d;
  array[d_int, 2, 3] matrix[d_int, d_int] d_matrix_array_3d;
  array[d_int, 2, 3] row_vector[d_int] d_row_vector_array_3d;


}

transformed data {
  int td_int;
  real td_real;
  vector[d_int] td_vector;
  matrix[d_int, d_int] td_matrix;
  row_vector[d_int] td_row_vector;
  array[d_int] real td_real_array_1d;
  array[d_int, 2] real td_real_array_2d;
  array[d_int, 2, 3] real td_real_array_3d;
  array[d_int] vector[d_int] td_vector_array_1d;
  array[d_int, 2] vector[d_int] td_vector_array_2d;
  array[d_int, 2, 3] vector[d_int] td_vector_array_3d;
  array[d_int] matrix[d_int, d_int] td_matrix_array_1d;
  array[d_int] row_vector[d_int] td_row_vector_array_1d;
  array[d_int, 2] matrix[d_int, d_int] td_matrix_array_2d;
  array[d_int, 2] row_vector[d_int] td_row_vector_array_2d;
  array[d_int, 2, 3] matrix[d_int, d_int] td_matrix_array_3d;
  array[d_int, 2, 3] row_vector[d_int] td_row_vector_array_3d;

  td_matrix = offset_multiplier_constrain(d_matrix, d_matrix, d_matrix);
  td_matrix = offset_multiplier_constrain(d_matrix, d_matrix, d_real);
  td_matrix = offset_multiplier_constrain(d_matrix, d_real, d_real);
  td_matrix = offset_multiplier_constrain(d_matrix, d_real, d_matrix);
  td_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_matrix_array_1d, d_matrix_array_1d);
  td_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_matrix_array_1d, d_real);
  td_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_real, d_real);
  td_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_real, d_matrix_array_1d);
  td_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_matrix_array_2d, d_matrix_array_2d);
  td_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_matrix_array_2d, d_real);
  td_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_real, d_real);
  td_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_real, d_matrix_array_2d);
  td_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_matrix_array_3d, d_matrix_array_3d);
  td_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_matrix_array_3d, d_real);
  td_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_real, d_real);
  td_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_real, d_matrix_array_3d);
  td_real = offset_multiplier_constrain(d_real, d_real, d_real);
  td_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real, d_real_array_1d);
  td_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real_array_1d, d_real);
  td_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real, d_real);
  td_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real_array_1d, d_real_array_1d);
  td_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real, d_real_array_2d);
  td_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real_array_2d, d_real);
  td_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real, d_real);
  td_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real_array_2d, d_real_array_2d);
  td_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real, d_real_array_3d);
  td_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real_array_3d, d_real);
  td_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real, d_real);
  td_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real_array_3d, d_real_array_3d);
  td_row_vector = offset_multiplier_constrain(d_row_vector, d_real, d_row_vector);
  td_row_vector = offset_multiplier_constrain(d_row_vector, d_row_vector, d_real);
  td_row_vector = offset_multiplier_constrain(d_row_vector, d_real, d_real);
  td_row_vector = offset_multiplier_constrain(d_row_vector, d_row_vector, d_row_vector);
  td_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_real, d_row_vector_array_1d);
  td_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_row_vector_array_1d, d_real);
  td_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_real, d_real);
  td_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_row_vector_array_1d, d_row_vector_array_1d);
  td_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_real, d_row_vector_array_2d);
  td_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_row_vector_array_2d, d_real);
  td_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_real, d_real);
  td_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_row_vector_array_2d, d_row_vector_array_2d);
  td_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_real, d_row_vector_array_3d);
  td_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_row_vector_array_3d, d_real);
  td_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_real, d_real);
  td_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_row_vector_array_3d, d_row_vector_array_3d);
  td_vector = offset_multiplier_constrain(d_vector, d_real, d_vector);
  td_vector = offset_multiplier_constrain(d_vector, d_vector, d_real);
  td_vector = offset_multiplier_constrain(d_vector, d_real, d_real);
  td_vector = offset_multiplier_constrain(d_vector, d_vector, d_vector);
  td_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_real, d_vector_array_1d);
  td_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_vector_array_1d, d_real);
  td_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_real, d_real);
  td_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_vector_array_1d, d_vector_array_1d);
  td_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_real, d_vector_array_2d);
  td_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_vector_array_2d, d_real);
  td_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_real, d_real);
  td_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_vector_array_2d, d_vector_array_2d);
  td_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_real, d_vector_array_3d);
  td_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_vector_array_3d, d_real);
  td_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_real, d_real);
  td_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_vector_array_3d, d_vector_array_3d);
}

parameters {
  real p_real;
  vector[d_int] p_vector;
  matrix[d_int, d_int] p_matrix;
  row_vector[d_int] p_row_vector;
  array[d_int] real p_real_array_1d;
  array[d_int, 2] real p_real_array_2d;
  array[d_int, 2, 3] real p_real_array_3d;
  array[d_int] vector[d_int] p_vector_array_1d;
  array[d_int, 2] vector[d_int] p_vector_array_2d;
  array[d_int, 2, 3] vector[d_int] p_vector_array_3d;
  array[d_int] matrix[d_int, d_int] p_matrix_array_1d;
  array[d_int] row_vector[d_int] p_row_vector_array_1d;
  array[d_int, 2] matrix[d_int, d_int] p_matrix_array_2d;
  array[d_int, 2] row_vector[d_int] p_row_vector_array_2d;
  array[d_int, 2, 3] matrix[d_int, d_int] p_matrix_array_3d;
  array[d_int, 2, 3] row_vector[d_int] p_row_vector_array_3d;


}

transformed parameters {
  real transformed_param_real;
  vector[d_int] transformed_param_vector;
  matrix[d_int, d_int] transformed_param_matrix;
  row_vector[d_int] transformed_param_row_vector;
  array[d_int] real transformed_param_real_array_1d;
  array[d_int, 2] real transformed_param_real_array_2d;
  array[d_int, 2, 3] real transformed_param_real_array_3d;
  array[d_int] vector[d_int] transformed_param_vector_array_1d;
  array[d_int, 2] vector[d_int] transformed_param_vector_array_2d;
  array[d_int, 2, 3] vector[d_int] transformed_param_vector_array_3d;
  array[d_int] matrix[d_int, d_int] transformed_param_matrix_array_1d;
  array[d_int] row_vector[d_int] transformed_param_row_vector_array_1d;
  array[d_int, 2] matrix[d_int, d_int] transformed_param_matrix_array_2d;
  array[d_int, 2] row_vector[d_int] transformed_param_row_vector_array_2d;
  array[d_int, 2, 3] matrix[d_int, d_int] transformed_param_matrix_array_3d;
  array[d_int, 2, 3] row_vector[d_int] transformed_param_row_vector_array_3d;

  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_matrix, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_matrix, d_real);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_real, d_real);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_matrix, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_matrix, p_real);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_real, p_real);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_real, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, d_real, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_matrix, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_matrix, d_real);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_matrix, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_matrix, p_real);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_real, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(d_matrix, p_real, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_matrix, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_matrix, d_real);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_real, d_real);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_matrix, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_matrix, p_real);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_real, p_real);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_real, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, d_real, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_matrix, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_matrix, d_real);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_matrix, p_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_matrix, p_real);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_real, d_matrix);
  transformed_param_matrix = offset_multiplier_constrain(p_matrix, p_real, p_matrix);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_matrix_array_1d, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_matrix_array_1d, d_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_real, d_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_matrix_array_1d, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_matrix_array_1d, p_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_real, p_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_real, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, d_real, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_matrix_array_1d, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_matrix_array_1d, d_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_matrix_array_1d, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_matrix_array_1d, p_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_real, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(d_matrix_array_1d, p_real, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_matrix_array_1d, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_matrix_array_1d, d_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_real, d_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_matrix_array_1d, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_matrix_array_1d, p_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_real, p_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_real, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, d_real, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_matrix_array_1d, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_matrix_array_1d, d_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_matrix_array_1d, p_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_matrix_array_1d, p_real);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_real, d_matrix_array_1d);
  transformed_param_matrix_array_1d = offset_multiplier_constrain(p_matrix_array_1d, p_real, p_matrix_array_1d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_matrix_array_2d, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_matrix_array_2d, d_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_real, d_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_matrix_array_2d, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_matrix_array_2d, p_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_real, p_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_real, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, d_real, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_matrix_array_2d, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_matrix_array_2d, d_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_matrix_array_2d, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_matrix_array_2d, p_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_real, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(d_matrix_array_2d, p_real, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_matrix_array_2d, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_matrix_array_2d, d_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_real, d_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_matrix_array_2d, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_matrix_array_2d, p_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_real, p_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_real, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, d_real, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_matrix_array_2d, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_matrix_array_2d, d_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_matrix_array_2d, p_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_matrix_array_2d, p_real);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_real, d_matrix_array_2d);
  transformed_param_matrix_array_2d = offset_multiplier_constrain(p_matrix_array_2d, p_real, p_matrix_array_2d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_matrix_array_3d, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_matrix_array_3d, d_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_real, d_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_matrix_array_3d, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_matrix_array_3d, p_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_real, p_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_real, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, d_real, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_matrix_array_3d, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_matrix_array_3d, d_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_matrix_array_3d, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_matrix_array_3d, p_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_real, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(d_matrix_array_3d, p_real, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_matrix_array_3d, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_matrix_array_3d, d_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_real, d_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_matrix_array_3d, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_matrix_array_3d, p_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_real, p_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_real, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, d_real, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_matrix_array_3d, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_matrix_array_3d, d_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_matrix_array_3d, p_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_matrix_array_3d, p_real);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_real, d_matrix_array_3d);
  transformed_param_matrix_array_3d = offset_multiplier_constrain(p_matrix_array_3d, p_real, p_matrix_array_3d);
  transformed_param_real = offset_multiplier_constrain(d_real, d_real, d_real);
  transformed_param_real = offset_multiplier_constrain(d_real, d_real, p_real);
  transformed_param_real = offset_multiplier_constrain(d_real, p_real, p_real);
  transformed_param_real = offset_multiplier_constrain(d_real, p_real, d_real);
  transformed_param_real = offset_multiplier_constrain(p_real, d_real, d_real);
  transformed_param_real = offset_multiplier_constrain(p_real, d_real, p_real);
  transformed_param_real = offset_multiplier_constrain(p_real, p_real, p_real);
  transformed_param_real = offset_multiplier_constrain(p_real, p_real, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real_array_1d, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real_array_1d, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real_array_1d, p_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real, p_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, d_real_array_1d, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real_array_1d, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real_array_1d, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real_array_1d, p_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(d_real_array_1d, p_real_array_1d, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real_array_1d, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real_array_1d, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real_array_1d, p_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real, p_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, d_real_array_1d, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real, p_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real_array_1d, d_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real_array_1d, d_real_array_1d);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real_array_1d, p_real);
  transformed_param_real_array_1d = offset_multiplier_constrain(p_real_array_1d, p_real_array_1d, p_real_array_1d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real_array_2d, d_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real, d_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real_array_2d, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real_array_2d, p_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real, p_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, d_real_array_2d, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real_array_2d, d_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real_array_2d, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real_array_2d, p_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(d_real_array_2d, p_real_array_2d, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real_array_2d, d_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real, d_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real_array_2d, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real_array_2d, p_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real, p_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, d_real_array_2d, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real, p_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real_array_2d, d_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real_array_2d, d_real_array_2d);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real_array_2d, p_real);
  transformed_param_real_array_2d = offset_multiplier_constrain(p_real_array_2d, p_real_array_2d, p_real_array_2d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real_array_3d, d_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real, d_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real_array_3d, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real_array_3d, p_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real, p_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, d_real_array_3d, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real_array_3d, d_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real_array_3d, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real_array_3d, p_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(d_real_array_3d, p_real_array_3d, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real_array_3d, d_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real, d_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real_array_3d, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real_array_3d, p_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real, p_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, d_real_array_3d, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real, p_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real_array_3d, d_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real_array_3d, d_real_array_3d);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real_array_3d, p_real);
  transformed_param_real_array_3d = offset_multiplier_constrain(p_real_array_3d, p_real_array_3d, p_real_array_3d);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_real, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_real, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_row_vector, d_real);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_real, d_real);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_row_vector, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_row_vector, p_real);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_real, p_real);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, d_row_vector, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_real, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_real, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_row_vector, d_real);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_row_vector, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_row_vector, p_real);
  transformed_param_row_vector = offset_multiplier_constrain(d_row_vector, p_row_vector, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_real, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_real, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_row_vector, d_real);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_real, d_real);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_row_vector, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_row_vector, p_real);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_real, p_real);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, d_row_vector, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_real, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_real, p_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_row_vector, d_real);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_row_vector, d_row_vector);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_row_vector, p_real);
  transformed_param_row_vector = offset_multiplier_constrain(p_row_vector, p_row_vector, p_row_vector);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_real, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_real, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_row_vector_array_1d, d_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_real, d_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_row_vector_array_1d, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_row_vector_array_1d, p_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_real, p_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, d_row_vector_array_1d, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_real, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_real, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_row_vector_array_1d, d_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_row_vector_array_1d, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_row_vector_array_1d, p_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(d_row_vector_array_1d, p_row_vector_array_1d, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_real, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_real, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_row_vector_array_1d, d_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_real, d_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_row_vector_array_1d, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_row_vector_array_1d, p_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_real, p_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, d_row_vector_array_1d, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_real, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_real, p_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_row_vector_array_1d, d_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_row_vector_array_1d, d_row_vector_array_1d);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_row_vector_array_1d, p_real);
  transformed_param_row_vector_array_1d = offset_multiplier_constrain(p_row_vector_array_1d, p_row_vector_array_1d, p_row_vector_array_1d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_real, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_real, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_row_vector_array_2d, d_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_real, d_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_row_vector_array_2d, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_row_vector_array_2d, p_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_real, p_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, d_row_vector_array_2d, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_real, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_real, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_row_vector_array_2d, d_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_row_vector_array_2d, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_row_vector_array_2d, p_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(d_row_vector_array_2d, p_row_vector_array_2d, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_real, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_real, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_row_vector_array_2d, d_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_real, d_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_row_vector_array_2d, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_row_vector_array_2d, p_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_real, p_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, d_row_vector_array_2d, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_real, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_real, p_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_row_vector_array_2d, d_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_row_vector_array_2d, d_row_vector_array_2d);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_row_vector_array_2d, p_real);
  transformed_param_row_vector_array_2d = offset_multiplier_constrain(p_row_vector_array_2d, p_row_vector_array_2d, p_row_vector_array_2d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_real, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_real, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_row_vector_array_3d, d_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_real, d_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_row_vector_array_3d, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_row_vector_array_3d, p_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_real, p_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, d_row_vector_array_3d, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_real, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_real, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_row_vector_array_3d, d_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_row_vector_array_3d, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_row_vector_array_3d, p_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(d_row_vector_array_3d, p_row_vector_array_3d, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_real, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_real, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_row_vector_array_3d, d_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_real, d_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_row_vector_array_3d, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_row_vector_array_3d, p_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_real, p_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, d_row_vector_array_3d, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_real, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_real, p_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_row_vector_array_3d, d_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_row_vector_array_3d, d_row_vector_array_3d);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_row_vector_array_3d, p_real);
  transformed_param_row_vector_array_3d = offset_multiplier_constrain(p_row_vector_array_3d, p_row_vector_array_3d, p_row_vector_array_3d);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_real, d_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_real, p_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_vector, d_real);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_real, d_real);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_vector, d_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_vector, p_real);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_real, p_real);
  transformed_param_vector = offset_multiplier_constrain(d_vector, d_vector, p_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_real, d_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_real, p_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_vector, d_real);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_vector, d_vector);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_vector, p_real);
  transformed_param_vector = offset_multiplier_constrain(d_vector, p_vector, p_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_real, d_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_real, p_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_vector, d_real);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_real, d_real);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_vector, d_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_vector, p_real);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_real, p_real);
  transformed_param_vector = offset_multiplier_constrain(p_vector, d_vector, p_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_real, d_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_real, p_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_vector, d_real);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_vector, d_vector);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_vector, p_real);
  transformed_param_vector = offset_multiplier_constrain(p_vector, p_vector, p_vector);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_real, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_real, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_vector_array_1d, d_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_real, d_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_vector_array_1d, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_vector_array_1d, p_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_real, p_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, d_vector_array_1d, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_real, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_real, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_vector_array_1d, d_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_vector_array_1d, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_vector_array_1d, p_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(d_vector_array_1d, p_vector_array_1d, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_real, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_real, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_vector_array_1d, d_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_real, d_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_vector_array_1d, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_vector_array_1d, p_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_real, p_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, d_vector_array_1d, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_real, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_real, p_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_vector_array_1d, d_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_vector_array_1d, d_vector_array_1d);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_vector_array_1d, p_real);
  transformed_param_vector_array_1d = offset_multiplier_constrain(p_vector_array_1d, p_vector_array_1d, p_vector_array_1d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_real, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_real, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_vector_array_2d, d_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_real, d_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_vector_array_2d, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_vector_array_2d, p_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_real, p_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, d_vector_array_2d, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_real, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_real, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_vector_array_2d, d_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_vector_array_2d, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_vector_array_2d, p_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(d_vector_array_2d, p_vector_array_2d, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_real, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_real, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_vector_array_2d, d_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_real, d_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_vector_array_2d, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_vector_array_2d, p_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_real, p_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, d_vector_array_2d, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_real, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_real, p_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_vector_array_2d, d_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_vector_array_2d, d_vector_array_2d);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_vector_array_2d, p_real);
  transformed_param_vector_array_2d = offset_multiplier_constrain(p_vector_array_2d, p_vector_array_2d, p_vector_array_2d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_real, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_real, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_vector_array_3d, d_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_real, d_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_vector_array_3d, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_vector_array_3d, p_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_real, p_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, d_vector_array_3d, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_real, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_real, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_vector_array_3d, d_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_vector_array_3d, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_vector_array_3d, p_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(d_vector_array_3d, p_vector_array_3d, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_real, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_real, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_vector_array_3d, d_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_real, d_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_vector_array_3d, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_vector_array_3d, p_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_real, p_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, d_vector_array_3d, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_real, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_real, p_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_vector_array_3d, d_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_vector_array_3d, d_vector_array_3d);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_vector_array_3d, p_real);
  transformed_param_vector_array_3d = offset_multiplier_constrain(p_vector_array_3d, p_vector_array_3d, p_vector_array_3d);
}

