lib: [
  "_build/install/default/lib/stanc/META" {"META"}
  "_build/install/default/lib/stanc/dune-package" {"dune-package"}
  "_build/install/default/lib/stanc/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/run_bin_on_args" {"run_bin_on_args"}
  "_build/install/default/bin/stan2tfp" {"stan2tfp"}
  "_build/install/default/bin/stanc" {"stanc"}
]
doc: [
  "_build/install/default/doc/stanc/LICENSE.txt"
  "_build/install/default/doc/stanc/README.md"
]
