(library
 (name middle)
 (public_name stanc.middle)
 (libraries base stdio fmt common)
 (instrumentation
  (backend bisect_ppx))
 (inline_tests)
 (preprocess
  (pps
   ppx_base
   ppx_pipebang
   ppx_sexp_message
   ppx_sexp_value
   ppx_expect
   ppx_inline_test
   ppx_deriving.map
   ppx_deriving.fold
   ppx_deriving.create)))
