(library
 (name stan_math_backend)
 (public_name stanc.stan_math_backend)
 (libraries base stdio fmt yojson middle stan_math_signatures)
 (instrumentation
  (backend bisect_ppx))
 (private_modules
  mangle
  cpp_Json
  cpp_str
  lower_expr
  lower_stmt
  lower_functions
  numbering)
 (inline_tests)
 (preprocess
  (pps
   ppx_base
   ppx_pipebang
   ppx_sexp_message
   ppx_sexp_value
   ppx_expect
   ppx_inline_test
   ppx_deriving.make)))
