blank_issues_enabled: false
contact_links:
  - name: Question about using Stan, modeling, etc
    url: https://discourse.mc-stan.org/
    about: |
      Ask questions and discuss with other community members here.
      If your question involves a specific model, including it will
      improve the quality of help the community can provide.
