(library
 (name analysis_and_optimization)
 (public_name stanc.analysis)
 (libraries base stdio middle yojson frontend stan_math_signatures)
 (instrumentation
  (backend bisect_ppx))
 (inline_tests)
 (modules_without_implementation monotone_framework_sigs)
 (preprocess
  (pps
   ppx_base
   ppx_pipebang
   ppx_sexp_message
   ppx_sexp_value
   ppx_expect
   ppx_inline_test)))
