(library
 (name stan_math_signatures)
 (public_name stanc.stan_math_signatures)
 (libraries fmt common middle)
 (instrumentation
  (backend bisect_ppx))
 (modules :standard \ generate)
 (private_modules generated_signatures)
 (inline_tests)
 (preprocess
  (pps ppx_inline_test)))

(executable
 (name generate)
 (modules generate)
 (preprocess
  (pps ppx_deriving.show))
 (libraries common middle))

(rule
 (with-stdout-to
  Generated_signatures.ml
  (run ./generate.exe)))
