(library
 (name driver)
 (public_name stanc.driver)
 (libraries
  base
  stdio
  fmt
  frontend
  middle
  stan_math_backend
  analysis_and_optimization)
 (instrumentation
  (backend bisect_ppx))
 (inline_tests)
 (preprocess
  (pps
   ppx_base
   ppx_pipebang
   ppx_sexp_message
   ppx_sexp_value
   ppx_expect
   ppx_inline_test)))
