(** Generate dune rules that pin one expected file per Stan model and per
    command, so a test folder does not have to list its model names.

    Usage: [gen_expected_rules.exe NAME:FLAGS ... -- model.stan ...]

    For every [NAME:FLAGS] argument and every [model.stan], emits a rule that
    runs [stanc FLAGS model.stan] through [run_bin_on_args] into
    [model.NAME.output] and a [runtest] rule that diffs it against
    [model.NAME.expected]. The folder's [dune] file includes the result via
    [(include dune.inc)] with [(mode promote)], so the generated file is checked
    in and refreshed whenever the set of models changes. *)

open Std

(* [model] is a path valid both from the generating rule's directory and from
   the directory that includes the generated rules (siblings, e.g.
   [../models/x.stan]); the outputs are named by the model's base name *)
let rule ~name ~flags model =
  let base = Filename.basename model |> String.chop_suffix_exn ~suffix:".stan" in
  Printf.printf
    {|(rule
 (targets %s.%s.output)
 (deps (package stanc) %s)
 (action
  (with-stdout-to %%{targets}
   (run %%{project_root}/test/integration/run_bin_on_args.exe
    "%%{bin:stanc} %s" %s))))

(rule
 (alias runtest)
 (action (diff %s.%s.expected %s.%s.output)))

|}
    base name model flags model base name base name

let () =
  let args = match Array.to_list Sys.argv with _ :: args -> args | [] -> [] in
  let rec split_at_dashes specs = function
    | "--" :: models -> (List.rev specs, models)
    | spec :: rest -> split_at_dashes (spec :: specs) rest
    | [] ->
        failwith "usage: gen_expected_rules NAME:FLAGS ... -- model.stan ..."
  in
  let specs, models = split_at_dashes [] args in
  let specs =
    List.map specs ~f:(fun spec ->
        match String.index_opt spec ':' with
        | Some i ->
            ( String.sub spec ~pos:0 ~len:i
            , String.sub spec ~pos:(i + 1) ~len:(String.length spec - i - 1) )
        | None -> failwith ("expected NAME:FLAGS, got " ^ spec)) in
  let models = List.sort models ~cmp:String.compare in
  print_string
    "; Generated by test/integration/gen_expected_rules.ml from the .stan \
     files in this folder; do not edit.\n\n";
  List.iter specs ~f:(fun (name, flags) ->
      List.iter models ~f:(rule ~name ~flags))
