(** Generate dune rules that pin one expected file per Stan model and per
    command, so a test folder does not have to list its model names.

    Usage: [gen_expected_rules.exe NAME:FLAGS ... -- model.stan ...]

    For every [NAME:FLAGS] argument and every [model.stan], emits a rule that
    runs [stanc FLAGS model.stan] through [run_bin_on_args] into
    [model.NAME.output] and a [runtest] rule that diffs it against
    [model.NAME.expected]. The folder's [dune] file loads the result through
    [(dynamic_include ...)], so the rules follow the set of models. *)

open Std

(* [model] is a path valid both from the generating rule's directory and from
   the directory that includes the generated rules (siblings, e.g.
   [../models/x.stan]). The command runs from the model's directory, so the
   locations in the output and the command shown name [x.stan] alone; the
   outputs are named by the model's base name. *)
let rule ~name ~flags model =
  let file = Filename.basename model in
  let base = String.chop_suffix_exn file ~suffix:".stan" in
  Printf.printf
    {|(rule
 (targets %s.%s.output)
 (deps (package stanc) %s)
 (action
  (with-stdout-to %%{targets}
   (chdir %s
    (run %%{project_root}/test/integration/run_bin_on_args.exe
     "%%{bin:stanc} %s" %s)))))

(rule
 (alias runtest)
 (action (diff %s.%s.expected %s.%s.output)))

|}
    base name model (Filename.dirname model) flags file base name base name

let () =
  let args = Option.value ~default:[] (List.tl (Array.to_list Sys.argv)) in
  let is_spec arg = not (String.equal arg "--") in
  let specs, models =
    match List.drop_while args ~f:is_spec with
    | "--" :: models -> (List.take_while args ~f:is_spec, models)
    | _ -> failwith "usage: gen_expected_rules NAME:FLAGS ... -- model.stan ..."
  in
  let specs =
    List.map specs ~f:(fun spec ->
        match String.split_first ~sep:":" spec with
        | Some spec -> spec
        | None -> failwith ("expected NAME:FLAGS, got " ^ spec)) in
  print_string
    "; Generated by test/integration/gen_expected_rules.ml from the .stan \
     files in this folder; do not edit.\n\n";
  List.iter specs ~f:(fun (name, flags) ->
      List.iter (List.sort models ~cmp:String.compare) ~f:(rule ~name ~flags))
